// <auto-generated />
using System;
using IcePlant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IcePlant.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508220711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Basin.BasinAggregate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<double>("FreezeHours")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BasinStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_basin_singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Basin.ProductionCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlocksAdded")
                        .HasColumnType("int");

                    b.Property<int>("LedgerDayId")
                        .HasColumnType("int");

                    b.Property<int>("StockAfter")
                        .HasColumnType("int");

                    b.Property<int>("StockBefore")
                        .HasColumnType("int");

                    b.Property<int>("TriggerReason")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LedgerDayId", "TriggeredAt");

                    b.ToTable("production_cycles", null, t =>
                        {
                            t.HasCheckConstraint("CK_production_blocks_positive", "[BlocksAdded] > 0");
                        });
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Finance.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceRef")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LedgerDayId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LedgerDayId");

                    b.ToTable("Expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_expenses_amount_positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Finance.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UtilityType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExpenseCategories", (string)null);
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Finance.LedgerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClosingStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("DayDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OpeningStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DayDate")
                        .IsUnique();

                    b.ToTable("LedgerDays", (string)null);
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Finance.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlocksSold")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LedgerDayId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("SaleTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LedgerDayId", "SaleTime");

                    b.ToTable("Sales", null, t =>
                        {
                            t.HasCheckConstraint("CK_sales_blocks_positive", "[BlocksSold] > 0");
                        });
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.HR.DailyAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<int>("LedgerDayId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LedgerDayId");

                    b.HasIndex("WorkerId");

                    b.ToTable("DailyAttendances", (string)null);
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.HR.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("HiredAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Monthly.MonthlySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateOnly>("MonthYear")
                        .HasColumnType("date");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlySummaries", null, t =>
                        {
                            t.HasCheckConstraint("CK_monthly_month_range", "[Month] >= 1 AND [Month] <= 12");
                        });
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Monthly.ProfitSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MonthlySummaryId")
                        .HasColumnType("int");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MonthlySummaryId");

                    b.ToTable("ProfitSplits", null, t =>
                        {
                            t.HasCheckConstraint("CK_split_pct_range", "[SplitPercentage] > 0 AND [SplitPercentage] <= 100");
                        });
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Basin.ProductionCycle", b =>
                {
                    b.HasOne("IcePlant.Domain.Aggregates.Finance.LedgerDay", null)
                        .WithMany()
                        .HasForeignKey("LedgerDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Finance.Expense", b =>
                {
                    b.HasOne("IcePlant.Domain.Aggregates.Finance.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IcePlant.Domain.Aggregates.Finance.LedgerDay", null)
                        .WithMany("Expenses")
                        .HasForeignKey("LedgerDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("ExpenseId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(12,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Finance.Sale", b =>
                {
                    b.HasOne("IcePlant.Domain.Aggregates.Finance.LedgerDay", null)
                        .WithMany("Sales")
                        .HasForeignKey("LedgerDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<int>("SaleId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(12,2)")
                                .HasColumnName("TotalAmount");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<int>("SaleId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.Navigation("TotalAmount")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.HR.DailyAttendance", b =>
                {
                    b.HasOne("IcePlant.Domain.Aggregates.Finance.LedgerDay", null)
                        .WithMany()
                        .HasForeignKey("LedgerDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IcePlant.Domain.Aggregates.HR.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "WagePaid", b1 =>
                        {
                            b1.Property<int>("DailyAttendanceId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("WagePaidAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("WagePaidCurrency");

                            b1.HasKey("DailyAttendanceId");

                            b1.ToTable("DailyAttendances");

                            b1.WithOwner()
                                .HasForeignKey("DailyAttendanceId");
                        });

                    b.Navigation("WagePaid")
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.HR.Worker", b =>
                {
                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "DailyWage", b1 =>
                        {
                            b1.Property<int>("WorkerId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DailyWageAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("DailyWageCurrency");

                            b1.HasKey("WorkerId");

                            b1.ToTable("Workers");

                            b1.WithOwner()
                                .HasForeignKey("WorkerId");
                        });

                    b.Navigation("DailyWage")
                        .IsRequired();
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Monthly.MonthlySummary", b =>
                {
                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "NetProfit", b1 =>
                        {
                            b1.Property<int>("MonthlySummaryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(14,2)")
                                .HasColumnName("NetProfit");

                            b1.HasKey("MonthlySummaryId");

                            b1.ToTable("MonthlySummaries");

                            b1.WithOwner()
                                .HasForeignKey("MonthlySummaryId");
                        });

                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "TotalExpenses", b1 =>
                        {
                            b1.Property<int>("MonthlySummaryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(14,2)")
                                .HasColumnName("TotalExpenses");

                            b1.HasKey("MonthlySummaryId");

                            b1.ToTable("MonthlySummaries");

                            b1.WithOwner()
                                .HasForeignKey("MonthlySummaryId");
                        });

                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "TotalIncome", b1 =>
                        {
                            b1.Property<int>("MonthlySummaryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(14,2)")
                                .HasColumnName("TotalIncome");

                            b1.HasKey("MonthlySummaryId");

                            b1.ToTable("MonthlySummaries");

                            b1.WithOwner()
                                .HasForeignKey("MonthlySummaryId");
                        });

                    b.Navigation("NetProfit")
                        .IsRequired();

                    b.Navigation("TotalExpenses")
                        .IsRequired();

                    b.Navigation("TotalIncome")
                        .IsRequired();
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Monthly.ProfitSplit", b =>
                {
                    b.HasOne("IcePlant.Domain.Aggregates.Monthly.MonthlySummary", null)
                        .WithMany("ProfitSplits")
                        .HasForeignKey("MonthlySummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IcePlant.Domain.ValueObjects.Money", "AmountReceived", b1 =>
                        {
                            b1.Property<int>("ProfitSplitId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(14,2)")
                                .HasColumnName("AmountReceived");

                            b1.HasKey("ProfitSplitId");

                            b1.ToTable("ProfitSplits");

                            b1.WithOwner()
                                .HasForeignKey("ProfitSplitId");
                        });

                    b.OwnsOne("IcePlant.Domain.ValueObjects.SplitPercentage", "SplitPercentage", b1 =>
                        {
                            b1.Property<int>("ProfitSplitId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("SplitPercentage");

                            b1.HasKey("ProfitSplitId");

                            b1.ToTable("ProfitSplits");

                            b1.WithOwner()
                                .HasForeignKey("ProfitSplitId");
                        });

                    b.Navigation("AmountReceived")
                        .IsRequired();

                    b.Navigation("SplitPercentage")
                        .IsRequired();
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Finance.LedgerDay", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("IcePlant.Domain.Aggregates.Monthly.MonthlySummary", b =>
                {
                    b.Navigation("ProfitSplits");
                });
#pragma warning restore 612, 618
        }
    }
}
